apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
localization:
  - name: image
    file: ./hello-world/values.yaml
    image: image.repository
    resource:
      name: helloworld-image
