apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: vault
  namespace: ocm-system
spec:
  interval: 1m0s
  componentVersionRef:
    name: vault
    namespace: ocm-system
  resource:
    resourceRef:
      kind: Resource
      name: vault-helm
      namespace: ocm-system
  # configRef:
  #   resource:
  #     resourceRef:
  #       name: config
  snapshotTemplate:
    name: vault-helm-localized
    createFluxSource: true
