apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  targetNamespace: default
  sourceRef:
    kind: OCIRepository
    name: vault-helm-loc
  path: ./
