apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: vault-helm
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: vault
    namespace: ocm-system
  resource:
    name: helloworld-chart
  snapshotTemplate:
    name: vault-helm
